language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install: 
  - pip install -r test-requirements.txt
# Command to run tests
script: pytest tests/ssh_config_test.py
