language: python
dist: xenial
sudo: false
branches:
  only:
    - master
    - main
    - develop
python:
  - "3.8"
  - "3.9"
  - "3.10"
# command to install dependencies
install: 
  - pip install -r test-requirements.txt
# Command to run tests
script: python tests/ssh_config_test.py
