language: python
dist: xenial
sudo: false
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install: 
  - pip install -r test-requirements.txt
# Command to run tests
script: python tests/ssh_config_test.py
